# Generated by cucumber-sinatra. (2015-06-01 10:23:31 -0500)
ENV['RACK_ENV'] = 'test'
require 'rack/test'
require 'capybara'
require 'capybara/cucumber'
require 'rspec'
require 'coveralls'
require_relative '../../super_villain_tools.rb'
require_relative '../../overlord.rb'

Coveralls.wear!

Capybara.app = Overlord

class OverlordWorld
  include Capybara::DSL
  include RSpec::Expectations
  include RSpec::Matchers
end

World do
  OverlordWorld.new
end
